-- Jalankan file ini di Supabase SQL Editor
-- Mode auth: tabel users + password hash (tanpa Supabase Auth)
-- Versi ini aman untuk kondisi tabel users lama sudah dihapus.

create extension if not exists pgcrypto with schema extensions;

-- Bersihkan function lama agar signature selalu sinkron.
drop function if exists public.register_user(text, text, text);
drop function if exists public.login_user(text, text);
drop function if exists public.submit_quiz_score(uuid, text, integer, integer);
drop function if exists public.get_leaderboard_overall(integer);
drop function if exists public.get_leaderboard_by_quiz(text, integer);

-- Buat ulang tabel users dari nol.
create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  password_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quiz_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  quiz_code text not null,
  best_score integer not null default 0,
  total_questions integer not null default 0,
  attempt_count integer not null default 0,
  last_score integer not null default 0,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint quiz_scores_quiz_code_chk check (quiz_code in ('banjir', 'gempa_bumi', 'gunung_meletus', 'tsunami')),
  constraint quiz_scores_unique_user_quiz unique (user_id, quiz_code)
);

create unique index if not exists users_email_lower_unique
on public.users (lower(email));

create index if not exists quiz_scores_user_id_idx on public.quiz_scores(user_id);
create index if not exists quiz_scores_quiz_code_idx on public.quiz_scores(quiz_code);

-- Trigger untuk auto update kolom updated_at.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
before update on public.users
for each row
execute procedure public.set_updated_at();

drop trigger if exists quiz_scores_set_updated_at on public.quiz_scores;
create trigger quiz_scores_set_updated_at
before update on public.quiz_scores
for each row
execute procedure public.set_updated_at();

create or replace function public.register_user(
  p_name text,
  p_email text,
  p_password text
)
returns table (id uuid, name text, email text, created_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  if length(coalesce(trim(p_name), '')) = 0 then
    raise exception 'Nama wajib diisi';
  end if;

  if length(coalesce(trim(p_email), '')) = 0 then
    raise exception 'Email wajib diisi';
  end if;

  if length(coalesce(trim(p_password), '')) < 6 then
    raise exception 'Password minimal 6 karakter';
  end if;

  insert into public.users (name, email, password_hash)
  values (
    trim(p_name),
    lower(trim(p_email)),
    extensions.crypt(p_password, extensions.gen_salt('bf', 12))
  )
  returning users.id into v_id;

  return query
  select u.id, u.name, u.email, u.created_at
  from public.users u
  where u.id = v_id;
end;
$$;

create or replace function public.login_user(
  p_email text,
  p_password text
)
returns table (id uuid, name text, email text)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  select u.id, u.name, u.email
  from public.users u
  where lower(u.email) = lower(trim(p_email))
    and u.password_hash = extensions.crypt(p_password, u.password_hash)
  limit 1;
end;
$$;

create or replace function public.submit_quiz_score(
  p_user_id uuid,
  p_quiz_code text,
  p_score integer,
  p_total integer
)
returns table (
  out_user_id uuid,
  out_quiz_code text,
  out_best_score integer,
  out_total_questions integer,
  out_attempt_count integer,
  out_last_score integer
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_user_id is null then
    raise exception 'User tidak valid';
  end if;

  if p_quiz_code not in ('banjir', 'gempa_bumi', 'gunung_meletus', 'tsunami') then
    raise exception 'Quiz code tidak valid';
  end if;

  if p_total <= 0 then
    raise exception 'Total soal tidak valid';
  end if;

  if p_score < 0 or p_score > p_total then
    raise exception 'Skor tidak valid';
  end if;

  insert into public.quiz_scores (user_id, quiz_code, best_score, total_questions, attempt_count, last_score)
  values (p_user_id, p_quiz_code, p_score, p_total, 1, p_score)
  on conflict (user_id, quiz_code)
  do update
  set best_score = greatest(public.quiz_scores.best_score, excluded.best_score),
      total_questions = excluded.total_questions,
      attempt_count = public.quiz_scores.attempt_count + 1,
      last_score = excluded.last_score,
      updated_at = now();

  return query
  select qs.user_id, qs.quiz_code, qs.best_score, qs.total_questions, qs.attempt_count, qs.last_score
  from public.quiz_scores qs
  where qs.user_id = p_user_id and qs.quiz_code = p_quiz_code;
end;
$$;

create or replace function public.get_leaderboard_overall(
  p_limit integer default 20
)
returns table (
  rank_no bigint,
  user_id uuid,
  name text,
  email text,
  total_best_score bigint,
  total_max_score bigint,
  quiz_played_count bigint
)
language sql
security definer
set search_path = public
as $$
  with agg as (
    select
      u.id as user_id,
      u.name,
      u.email,
      coalesce(sum(qs.best_score), 0) as total_best_score,
      coalesce(sum(qs.total_questions), 0) as total_max_score,
      count(qs.id) as quiz_played_count
    from public.users u
    left join public.quiz_scores qs on qs.user_id = u.id
    group by u.id, u.name, u.email
  )
  select
    row_number() over (order by agg.total_best_score desc, agg.total_max_score desc, agg.name asc) as rank_no,
    agg.user_id,
    agg.name,
    agg.email,
    agg.total_best_score,
    agg.total_max_score,
    agg.quiz_played_count
  from agg
  where agg.quiz_played_count = 4
  order by agg.total_best_score desc, agg.total_max_score desc, agg.name asc
  limit greatest(coalesce(p_limit, 20), 1);
$$;

create or replace function public.get_leaderboard_by_quiz(
  p_quiz_code text,
  p_limit integer default 20
)
returns table (
  rank_no bigint,
  user_id uuid,
  name text,
  email text,
  best_score integer,
  total_questions integer,
  attempt_count integer
)
language sql
security definer
set search_path = public
as $$
  select
    row_number() over (order by qs.best_score desc, qs.total_questions desc, u.name asc) as rank_no,
    u.id as user_id,
    u.name,
    u.email,
    qs.best_score,
    qs.total_questions,
    qs.attempt_count
  from public.quiz_scores qs
  join public.users u on u.id = qs.user_id
  where qs.quiz_code = p_quiz_code
  order by qs.best_score desc, qs.total_questions desc, u.name asc
  limit greatest(coalesce(p_limit, 20), 1);
$$;

grant execute on function public.register_user(text, text, text) to anon, authenticated;
grant execute on function public.login_user(text, text) to anon, authenticated;
grant execute on function public.submit_quiz_score(uuid, text, integer, integer) to anon, authenticated;
grant execute on function public.get_leaderboard_overall(integer) to anon, authenticated;
grant execute on function public.get_leaderboard_by_quiz(text, integer) to anon, authenticated;
